// Package docs Code generated by swaggo/swag. DO NOT EDIT
// Run `make swagger` to regenerate from handler annotations.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns 200 OK when the service is alive.",
                "produces": ["application/json"],
                "tags": ["system"],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {"type": "string"}
                        }
                    }
                }
            }
        },
        "/api/v1/check": {
            "post": {
                "description": "Submits a caller_id and destination for scoring. Returns GREEN, YELLOW, or RED status.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["scoring"],
                "summary": "Score a call attempt",
                "parameters": [
                    {
                        "description": "Call details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.checkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/api.checkResponse"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"$ref": "#/definitions/api.errorResponse"}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {"$ref": "#/definitions/api.errorResponse"}
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Returns Redis-based counters for each call status category.",
                "produces": ["application/json"],
                "tags": ["scoring"],
                "summary": "Get aggregate call statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/api.statsResponse"}
                    }
                }
            }
        },
        "/api/v1/whitelist": {
            "get": {
                "description": "Returns all caller prefix entries in the whitelist.",
                "produces": ["application/json"],
                "tags": ["whitelist"],
                "summary": "List all whitelist entries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/scoring.WhitelistEntry"}
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a caller prefix to the whitelist with a label and tier override.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["whitelist"],
                "summary": "Add a whitelist entry",
                "parameters": [
                    {
                        "description": "Whitelist entry",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/api.whitelistRequest"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"$ref": "#/definitions/scoring.WhitelistEntry"}
                    }
                }
            }
        },
        "/api/v1/whitelist/{prefix}": {
            "delete": {
                "description": "Removes a caller prefix from the whitelist by prefix value.",
                "produces": ["application/json"],
                "tags": ["whitelist"],
                "summary": "Remove a whitelist entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Caller prefix",
                        "name": "prefix",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/api.messageResponse"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"$ref": "#/definitions/api.errorResponse"}
                    }
                }
            }
        }
    },
    "definitions": {
        "api.checkRequest": {
            "type": "object",
            "required": ["caller_id", "destination"],
            "properties": {
                "caller_id": {"type": "string", "example": "+46701234567"},
                "destination": {"type": "string", "example": "+46891234567"}
            }
        },
        "api.checkResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "example": "GREEN"},
                "score": {"type": "integer", "example": 5},
                "reason": {"type": "string"},
                "timestamp": {"type": "string", "format": "date-time"},
                "blocked": {"type": "boolean"}
            }
        },
        "api.statsResponse": {
            "type": "object",
            "properties": {
                "GREEN": {"type": "integer"},
                "YELLOW": {"type": "integer"},
                "RED": {"type": "integer"}
            }
        },
        "api.whitelistRequest": {
            "type": "object",
            "required": ["prefix", "label", "tier"],
            "properties": {
                "prefix": {"type": "string", "example": "+467"},
                "label": {"type": "string", "example": "Swedish mobile"},
                "tier": {"type": "string", "enum": ["GREEN","YELLOW","RED"], "example": "GREEN"}
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string"}
            }
        },
        "api.messageResponse": {
            "type": "object",
            "properties": {
                "message": {"type": "string"}
            }
        },
        "scoring.WhitelistEntry": {
            "type": "object",
            "properties": {
                "prefix": {"type": "string", "example": "+467"},
                "label": {"type": "string", "example": "Swedish mobile"},
                "tier": {"type": "string", "example": "GREEN"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SIP Guard API",
	Description:      "Production-ready Go backend service for SIP call scoring and fraud protection.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
